/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyHashRouteImport } from './routes/verify.$hash'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedRegistryRouteImport } from './routes/_authenticated/registry'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyLearningRouteImport } from './routes/_authenticated/my-learning'
import { Route as AuthenticatedMentorshipRouteImport } from './routes/_authenticated/mentorship'
import { Route as AuthenticatedLicenseRouteImport } from './routes/_authenticated/license'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCpdRouteImport } from './routes/_authenticated/cpd'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedSimulationsIndexRouteImport } from './routes/_authenticated/simulations.index'
import { Route as AuthenticatedSeminarsIndexRouteImport } from './routes/_authenticated/seminars.index'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams.index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedCertificatesIndexRouteImport } from './routes/_authenticated/certificates.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedSimulationsScenarioIdRouteImport } from './routes/_authenticated/simulations.$scenarioId'
import { Route as AuthenticatedSeminarsIdRouteImport } from './routes/_authenticated/seminars.$id'
import { Route as AuthenticatedDevTimelineRouteImport } from './routes/_authenticated/dev.timeline'
import { Route as AuthenticatedDevIncidentRouteImport } from './routes/_authenticated/dev.incident'
import { Route as AuthenticatedDevHallRouteImport } from './routes/_authenticated/dev.hall'
import { Route as AuthenticatedDevBoardRouteImport } from './routes/_authenticated/dev.board'
import { Route as AuthenticatedCertificatesIdRouteImport } from './routes/_authenticated/certificates.$id'
import { Route as AuthenticatedAdminSeminarsRouteImport } from './routes/_authenticated/admin.seminars'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminLicensesRouteImport } from './routes/_authenticated/admin.licenses'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminCpdRouteImport } from './routes/_authenticated/admin.cpd'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedExamsExamIdIndexRouteImport } from './routes/_authenticated/exams.$examId.index'
import { Route as AuthenticatedCoursesSlugIndexRouteImport } from './routes/_authenticated/courses.$slug.index'
import { Route as AuthenticatedAdminGradingIndexRouteImport } from './routes/_authenticated/admin.grading.index'
import { Route as AuthenticatedExamsExamIdAttemptRouteImport } from './routes/_authenticated/exams.$examId.attempt'
import { Route as AuthenticatedAdminSeminarsIdRouteImport } from './routes/_authenticated/admin.seminars.$id'
import { Route as AuthenticatedAdminGradingAttemptIdRouteImport } from './routes/_authenticated/admin.grading.$attemptId'
import { Route as AuthenticatedAdminCoursesIdRouteImport } from './routes/_authenticated/admin.courses.$id'
import { Route as AuthenticatedExamsExamIdResultAttemptIdRouteImport } from './routes/_authenticated/exams.$examId.result.$attemptId'
import { Route as AuthenticatedCoursesSlugLessonsLessonIdRouteImport } from './routes/_authenticated/courses.$slug.lessons.$lessonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyHashRoute = VerifyHashRouteImport.update({
  id: '/verify/$hash',
  path: '/verify/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistryRoute = AuthenticatedRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyLearningRoute = AuthenticatedMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMentorshipRoute = AuthenticatedMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLicenseRoute = AuthenticatedLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCpdRoute = AuthenticatedCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimulationsIndexRoute =
  AuthenticatedSimulationsIndexRouteImport.update({
    id: '/simulations/',
    path: '/simulations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeminarsIndexRoute =
  AuthenticatedSeminarsIndexRouteImport.update({
    id: '/seminars/',
    path: '/seminars/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCertificatesIndexRoute =
  AuthenticatedCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimulationsScenarioIdRoute =
  AuthenticatedSimulationsScenarioIdRouteImport.update({
    id: '/simulations/$scenarioId',
    path: '/simulations/$scenarioId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeminarsIdRoute = AuthenticatedSeminarsIdRouteImport.update({
  id: '/seminars/$id',
  path: '/seminars/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevTimelineRoute =
  AuthenticatedDevTimelineRouteImport.update({
    id: '/dev/timeline',
    path: '/dev/timeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevIncidentRoute =
  AuthenticatedDevIncidentRouteImport.update({
    id: '/dev/incident',
    path: '/dev/incident',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevHallRoute = AuthenticatedDevHallRouteImport.update({
  id: '/dev/hall',
  path: '/dev/hall',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevBoardRoute = AuthenticatedDevBoardRouteImport.update({
  id: '/dev/board',
  path: '/dev/board',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesIdRoute =
  AuthenticatedCertificatesIdRouteImport.update({
    id: '/certificates/$id',
    path: '/certificates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSeminarsRoute =
  AuthenticatedAdminSeminarsRouteImport.update({
    id: '/admin/seminars',
    path: '/admin/seminars',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/admin/resources',
    path: '/admin/resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLicensesRoute =
  AuthenticatedAdminLicensesRouteImport.update({
    id: '/admin/licenses',
    path: '/admin/licenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCpdRoute = AuthenticatedAdminCpdRouteImport.update({
  id: '/admin/cpd',
  path: '/admin/cpd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamIdIndexRoute =
  AuthenticatedExamsExamIdIndexRouteImport.update({
    id: '/exams/$examId/',
    path: '/exams/$examId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesSlugIndexRoute =
  AuthenticatedCoursesSlugIndexRouteImport.update({
    id: '/courses/$slug/',
    path: '/courses/$slug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGradingIndexRoute =
  AuthenticatedAdminGradingIndexRouteImport.update({
    id: '/admin/grading/',
    path: '/admin/grading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamIdAttemptRoute =
  AuthenticatedExamsExamIdAttemptRouteImport.update({
    id: '/exams/$examId/attempt',
    path: '/exams/$examId/attempt',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSeminarsIdRoute =
  AuthenticatedAdminSeminarsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSeminarsRoute,
  } as any)
const AuthenticatedAdminGradingAttemptIdRoute =
  AuthenticatedAdminGradingAttemptIdRouteImport.update({
    id: '/admin/grading/$attemptId',
    path: '/admin/grading/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCoursesIdRoute =
  AuthenticatedAdminCoursesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedExamsExamIdResultAttemptIdRoute =
  AuthenticatedExamsExamIdResultAttemptIdRouteImport.update({
    id: '/exams/$examId/result/$attemptId',
    path: '/exams/$examId/result/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesSlugLessonsLessonIdRoute =
  AuthenticatedCoursesSlugLessonsLessonIdRouteImport.update({
    id: '/courses/$slug/lessons/$lessonId',
    path: '/courses/$slug/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/cpd': typeof AuthenticatedCpdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/cpd': typeof AuthenticatedAdminCpdRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/seminars': typeof AuthenticatedAdminSeminarsRouteWithChildren
  '/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/dev/board': typeof AuthenticatedDevBoardRoute
  '/dev/hall': typeof AuthenticatedDevHallRoute
  '/dev/incident': typeof AuthenticatedDevIncidentRoute
  '/dev/timeline': typeof AuthenticatedDevTimelineRoute
  '/seminars/$id': typeof AuthenticatedSeminarsIdRoute
  '/simulations/$scenarioId': typeof AuthenticatedSimulationsScenarioIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/seminars/': typeof AuthenticatedSeminarsIndexRoute
  '/simulations/': typeof AuthenticatedSimulationsIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/admin/grading/$attemptId': typeof AuthenticatedAdminGradingAttemptIdRoute
  '/admin/seminars/$id': typeof AuthenticatedAdminSeminarsIdRoute
  '/exams/$examId/attempt': typeof AuthenticatedExamsExamIdAttemptRoute
  '/admin/grading/': typeof AuthenticatedAdminGradingIndexRoute
  '/courses/$slug/': typeof AuthenticatedCoursesSlugIndexRoute
  '/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
  '/courses/$slug/lessons/$lessonId': typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  '/exams/$examId/result/$attemptId': typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/cpd': typeof AuthenticatedCpdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/cpd': typeof AuthenticatedAdminCpdRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/seminars': typeof AuthenticatedAdminSeminarsRouteWithChildren
  '/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/dev/board': typeof AuthenticatedDevBoardRoute
  '/dev/hall': typeof AuthenticatedDevHallRoute
  '/dev/incident': typeof AuthenticatedDevIncidentRoute
  '/dev/timeline': typeof AuthenticatedDevTimelineRoute
  '/seminars/$id': typeof AuthenticatedSeminarsIdRoute
  '/simulations/$scenarioId': typeof AuthenticatedSimulationsScenarioIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/certificates': typeof AuthenticatedCertificatesIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/seminars': typeof AuthenticatedSeminarsIndexRoute
  '/simulations': typeof AuthenticatedSimulationsIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/admin/grading/$attemptId': typeof AuthenticatedAdminGradingAttemptIdRoute
  '/admin/seminars/$id': typeof AuthenticatedAdminSeminarsIdRoute
  '/exams/$examId/attempt': typeof AuthenticatedExamsExamIdAttemptRoute
  '/admin/grading': typeof AuthenticatedAdminGradingIndexRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugIndexRoute
  '/exams/$examId': typeof AuthenticatedExamsExamIdIndexRoute
  '/courses/$slug/lessons/$lessonId': typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  '/exams/$examId/result/$attemptId': typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/cpd': typeof AuthenticatedCpdRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/license': typeof AuthenticatedLicenseRoute
  '/_authenticated/mentorship': typeof AuthenticatedMentorshipRoute
  '/_authenticated/my-learning': typeof AuthenticatedMyLearningRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/registry': typeof AuthenticatedRegistryRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/verify/$hash': typeof VerifyHashRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/cpd': typeof AuthenticatedAdminCpdRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/seminars': typeof AuthenticatedAdminSeminarsRouteWithChildren
  '/_authenticated/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/_authenticated/dev/board': typeof AuthenticatedDevBoardRoute
  '/_authenticated/dev/hall': typeof AuthenticatedDevHallRoute
  '/_authenticated/dev/incident': typeof AuthenticatedDevIncidentRoute
  '/_authenticated/dev/timeline': typeof AuthenticatedDevTimelineRoute
  '/_authenticated/seminars/$id': typeof AuthenticatedSeminarsIdRoute
  '/_authenticated/simulations/$scenarioId': typeof AuthenticatedSimulationsScenarioIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/seminars/': typeof AuthenticatedSeminarsIndexRoute
  '/_authenticated/simulations/': typeof AuthenticatedSimulationsIndexRoute
  '/_authenticated/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
  '/_authenticated/admin/grading/$attemptId': typeof AuthenticatedAdminGradingAttemptIdRoute
  '/_authenticated/admin/seminars/$id': typeof AuthenticatedAdminSeminarsIdRoute
  '/_authenticated/exams/$examId/attempt': typeof AuthenticatedExamsExamIdAttemptRoute
  '/_authenticated/admin/grading/': typeof AuthenticatedAdminGradingIndexRoute
  '/_authenticated/courses/$slug/': typeof AuthenticatedCoursesSlugIndexRoute
  '/_authenticated/exams/$examId/': typeof AuthenticatedExamsExamIdIndexRoute
  '/_authenticated/courses/$slug/lessons/$lessonId': typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  '/_authenticated/exams/$examId/result/$attemptId': typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/badges'
    | '/cpd'
    | '/dashboard'
    | '/license'
    | '/mentorship'
    | '/my-learning'
    | '/notifications'
    | '/practice'
    | '/profile'
    | '/promotions'
    | '/registry'
    | '/resources'
    | '/search'
    | '/security'
    | '/verify/$hash'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/cpd'
    | '/admin/exams'
    | '/admin/licenses'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/seminars'
    | '/certificates/$id'
    | '/dev/board'
    | '/dev/hall'
    | '/dev/incident'
    | '/dev/timeline'
    | '/seminars/$id'
    | '/simulations/$scenarioId'
    | '/api/public/bootstrap-admin'
    | '/admin/'
    | '/certificates/'
    | '/courses/'
    | '/exams/'
    | '/seminars/'
    | '/simulations/'
    | '/admin/courses/$id'
    | '/admin/grading/$attemptId'
    | '/admin/seminars/$id'
    | '/exams/$examId/attempt'
    | '/admin/grading/'
    | '/courses/$slug/'
    | '/exams/$examId/'
    | '/courses/$slug/lessons/$lessonId'
    | '/exams/$examId/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/badges'
    | '/cpd'
    | '/dashboard'
    | '/license'
    | '/mentorship'
    | '/my-learning'
    | '/notifications'
    | '/practice'
    | '/profile'
    | '/promotions'
    | '/registry'
    | '/resources'
    | '/search'
    | '/security'
    | '/verify/$hash'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/cpd'
    | '/admin/exams'
    | '/admin/licenses'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/seminars'
    | '/certificates/$id'
    | '/dev/board'
    | '/dev/hall'
    | '/dev/incident'
    | '/dev/timeline'
    | '/seminars/$id'
    | '/simulations/$scenarioId'
    | '/api/public/bootstrap-admin'
    | '/admin'
    | '/certificates'
    | '/courses'
    | '/exams'
    | '/seminars'
    | '/simulations'
    | '/admin/courses/$id'
    | '/admin/grading/$attemptId'
    | '/admin/seminars/$id'
    | '/exams/$examId/attempt'
    | '/admin/grading'
    | '/courses/$slug'
    | '/exams/$examId'
    | '/courses/$slug/lessons/$lessonId'
    | '/exams/$examId/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/badges'
    | '/_authenticated/cpd'
    | '/_authenticated/dashboard'
    | '/_authenticated/license'
    | '/_authenticated/mentorship'
    | '/_authenticated/my-learning'
    | '/_authenticated/notifications'
    | '/_authenticated/practice'
    | '/_authenticated/profile'
    | '/_authenticated/promotions'
    | '/_authenticated/registry'
    | '/_authenticated/resources'
    | '/_authenticated/search'
    | '/_authenticated/security'
    | '/verify/$hash'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/cpd'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/licenses'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/seminars'
    | '/_authenticated/certificates/$id'
    | '/_authenticated/dev/board'
    | '/_authenticated/dev/hall'
    | '/_authenticated/dev/incident'
    | '/_authenticated/dev/timeline'
    | '/_authenticated/seminars/$id'
    | '/_authenticated/simulations/$scenarioId'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/admin/'
    | '/_authenticated/certificates/'
    | '/_authenticated/courses/'
    | '/_authenticated/exams/'
    | '/_authenticated/seminars/'
    | '/_authenticated/simulations/'
    | '/_authenticated/admin/courses/$id'
    | '/_authenticated/admin/grading/$attemptId'
    | '/_authenticated/admin/seminars/$id'
    | '/_authenticated/exams/$examId/attempt'
    | '/_authenticated/admin/grading/'
    | '/_authenticated/courses/$slug/'
    | '/_authenticated/exams/$examId/'
    | '/_authenticated/courses/$slug/lessons/$lessonId'
    | '/_authenticated/exams/$examId/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyHashRoute: typeof VerifyHashRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$hash': {
      id: '/verify/$hash'
      path: '/verify/$hash'
      fullPath: '/verify/$hash'
      preLoaderRoute: typeof VerifyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry': {
      id: '/_authenticated/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-learning': {
      id: '/_authenticated/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AuthenticatedMyLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mentorship': {
      id: '/_authenticated/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AuthenticatedMentorshipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/license': {
      id: '/_authenticated/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AuthenticatedLicenseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cpd': {
      id: '/_authenticated/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof AuthenticatedCpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulations/': {
      id: '/_authenticated/simulations/'
      path: '/simulations'
      fullPath: '/simulations/'
      preLoaderRoute: typeof AuthenticatedSimulationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seminars/': {
      id: '/_authenticated/seminars/'
      path: '/seminars'
      fullPath: '/seminars/'
      preLoaderRoute: typeof AuthenticatedSeminarsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates/': {
      id: '/_authenticated/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthenticatedCertificatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simulations/$scenarioId': {
      id: '/_authenticated/simulations/$scenarioId'
      path: '/simulations/$scenarioId'
      fullPath: '/simulations/$scenarioId'
      preLoaderRoute: typeof AuthenticatedSimulationsScenarioIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seminars/$id': {
      id: '/_authenticated/seminars/$id'
      path: '/seminars/$id'
      fullPath: '/seminars/$id'
      preLoaderRoute: typeof AuthenticatedSeminarsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/timeline': {
      id: '/_authenticated/dev/timeline'
      path: '/dev/timeline'
      fullPath: '/dev/timeline'
      preLoaderRoute: typeof AuthenticatedDevTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/incident': {
      id: '/_authenticated/dev/incident'
      path: '/dev/incident'
      fullPath: '/dev/incident'
      preLoaderRoute: typeof AuthenticatedDevIncidentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/hall': {
      id: '/_authenticated/dev/hall'
      path: '/dev/hall'
      fullPath: '/dev/hall'
      preLoaderRoute: typeof AuthenticatedDevHallRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/board': {
      id: '/_authenticated/dev/board'
      path: '/dev/board'
      fullPath: '/dev/board'
      preLoaderRoute: typeof AuthenticatedDevBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates/$id': {
      id: '/_authenticated/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof AuthenticatedCertificatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/seminars': {
      id: '/_authenticated/admin/seminars'
      path: '/admin/seminars'
      fullPath: '/admin/seminars'
      preLoaderRoute: typeof AuthenticatedAdminSeminarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/licenses': {
      id: '/_authenticated/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AuthenticatedAdminLicensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cpd': {
      id: '/_authenticated/admin/cpd'
      path: '/admin/cpd'
      fullPath: '/admin/cpd'
      preLoaderRoute: typeof AuthenticatedAdminCpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examId/': {
      id: '/_authenticated/exams/$examId/'
      path: '/exams/$examId'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/$slug/': {
      id: '/_authenticated/courses/$slug/'
      path: '/courses/$slug'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof AuthenticatedCoursesSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/grading/': {
      id: '/_authenticated/admin/grading/'
      path: '/admin/grading'
      fullPath: '/admin/grading/'
      preLoaderRoute: typeof AuthenticatedAdminGradingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examId/attempt': {
      id: '/_authenticated/exams/$examId/attempt'
      path: '/exams/$examId/attempt'
      fullPath: '/exams/$examId/attempt'
      preLoaderRoute: typeof AuthenticatedExamsExamIdAttemptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/seminars/$id': {
      id: '/_authenticated/admin/seminars/$id'
      path: '/$id'
      fullPath: '/admin/seminars/$id'
      preLoaderRoute: typeof AuthenticatedAdminSeminarsIdRouteImport
      parentRoute: typeof AuthenticatedAdminSeminarsRoute
    }
    '/_authenticated/admin/grading/$attemptId': {
      id: '/_authenticated/admin/grading/$attemptId'
      path: '/admin/grading/$attemptId'
      fullPath: '/admin/grading/$attemptId'
      preLoaderRoute: typeof AuthenticatedAdminGradingAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/courses/$id': {
      id: '/_authenticated/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/exams/$examId/result/$attemptId': {
      id: '/_authenticated/exams/$examId/result/$attemptId'
      path: '/exams/$examId/result/$attemptId'
      fullPath: '/exams/$examId/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/$slug/lessons/$lessonId': {
      id: '/_authenticated/courses/$slug/lessons/$lessonId'
      path: '/courses/$slug/lessons/$lessonId'
      fullPath: '/courses/$slug/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedCoursesSlugLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesIdRoute: typeof AuthenticatedAdminCoursesIdRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesIdRoute: AuthenticatedAdminCoursesIdRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminSeminarsRouteChildren {
  AuthenticatedAdminSeminarsIdRoute: typeof AuthenticatedAdminSeminarsIdRoute
}

const AuthenticatedAdminSeminarsRouteChildren: AuthenticatedAdminSeminarsRouteChildren =
  {
    AuthenticatedAdminSeminarsIdRoute: AuthenticatedAdminSeminarsIdRoute,
  }

const AuthenticatedAdminSeminarsRouteWithChildren =
  AuthenticatedAdminSeminarsRoute._addFileChildren(
    AuthenticatedAdminSeminarsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedCpdRoute: typeof AuthenticatedCpdRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLicenseRoute: typeof AuthenticatedLicenseRoute
  AuthenticatedMentorshipRoute: typeof AuthenticatedMentorshipRoute
  AuthenticatedMyLearningRoute: typeof AuthenticatedMyLearningRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedRegistryRoute: typeof AuthenticatedRegistryRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminCpdRoute: typeof AuthenticatedAdminCpdRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminLicensesRoute: typeof AuthenticatedAdminLicensesRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSeminarsRoute: typeof AuthenticatedAdminSeminarsRouteWithChildren
  AuthenticatedCertificatesIdRoute: typeof AuthenticatedCertificatesIdRoute
  AuthenticatedDevBoardRoute: typeof AuthenticatedDevBoardRoute
  AuthenticatedDevHallRoute: typeof AuthenticatedDevHallRoute
  AuthenticatedDevIncidentRoute: typeof AuthenticatedDevIncidentRoute
  AuthenticatedDevTimelineRoute: typeof AuthenticatedDevTimelineRoute
  AuthenticatedSeminarsIdRoute: typeof AuthenticatedSeminarsIdRoute
  AuthenticatedSimulationsScenarioIdRoute: typeof AuthenticatedSimulationsScenarioIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCertificatesIndexRoute: typeof AuthenticatedCertificatesIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedSeminarsIndexRoute: typeof AuthenticatedSeminarsIndexRoute
  AuthenticatedSimulationsIndexRoute: typeof AuthenticatedSimulationsIndexRoute
  AuthenticatedAdminGradingAttemptIdRoute: typeof AuthenticatedAdminGradingAttemptIdRoute
  AuthenticatedExamsExamIdAttemptRoute: typeof AuthenticatedExamsExamIdAttemptRoute
  AuthenticatedAdminGradingIndexRoute: typeof AuthenticatedAdminGradingIndexRoute
  AuthenticatedCoursesSlugIndexRoute: typeof AuthenticatedCoursesSlugIndexRoute
  AuthenticatedExamsExamIdIndexRoute: typeof AuthenticatedExamsExamIdIndexRoute
  AuthenticatedCoursesSlugLessonsLessonIdRoute: typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  AuthenticatedExamsExamIdResultAttemptIdRoute: typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedCpdRoute: AuthenticatedCpdRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLicenseRoute: AuthenticatedLicenseRoute,
  AuthenticatedMentorshipRoute: AuthenticatedMentorshipRoute,
  AuthenticatedMyLearningRoute: AuthenticatedMyLearningRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedRegistryRoute: AuthenticatedRegistryRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
  AuthenticatedAdminCpdRoute: AuthenticatedAdminCpdRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
  AuthenticatedAdminLicensesRoute: AuthenticatedAdminLicensesRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminSeminarsRoute: AuthenticatedAdminSeminarsRouteWithChildren,
  AuthenticatedCertificatesIdRoute: AuthenticatedCertificatesIdRoute,
  AuthenticatedDevBoardRoute: AuthenticatedDevBoardRoute,
  AuthenticatedDevHallRoute: AuthenticatedDevHallRoute,
  AuthenticatedDevIncidentRoute: AuthenticatedDevIncidentRoute,
  AuthenticatedDevTimelineRoute: AuthenticatedDevTimelineRoute,
  AuthenticatedSeminarsIdRoute: AuthenticatedSeminarsIdRoute,
  AuthenticatedSimulationsScenarioIdRoute:
    AuthenticatedSimulationsScenarioIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCertificatesIndexRoute: AuthenticatedCertificatesIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedSeminarsIndexRoute: AuthenticatedSeminarsIndexRoute,
  AuthenticatedSimulationsIndexRoute: AuthenticatedSimulationsIndexRoute,
  AuthenticatedAdminGradingAttemptIdRoute:
    AuthenticatedAdminGradingAttemptIdRoute,
  AuthenticatedExamsExamIdAttemptRoute: AuthenticatedExamsExamIdAttemptRoute,
  AuthenticatedAdminGradingIndexRoute: AuthenticatedAdminGradingIndexRoute,
  AuthenticatedCoursesSlugIndexRoute: AuthenticatedCoursesSlugIndexRoute,
  AuthenticatedExamsExamIdIndexRoute: AuthenticatedExamsExamIdIndexRoute,
  AuthenticatedCoursesSlugLessonsLessonIdRoute:
    AuthenticatedCoursesSlugLessonsLessonIdRoute,
  AuthenticatedExamsExamIdResultAttemptIdRoute:
    AuthenticatedExamsExamIdResultAttemptIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyHashRoute: VerifyHashRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
