/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyHashRouteImport } from './routes/verify.$hash'
import { Route as AuthenticatedSeminarsRouteImport } from './routes/_authenticated/seminars'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedRegistryRouteImport } from './routes/_authenticated/registry'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyLearningRouteImport } from './routes/_authenticated/my-learning'
import { Route as AuthenticatedLicenseRouteImport } from './routes/_authenticated/license'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCpdRouteImport } from './routes/_authenticated/cpd'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedCertificatesIndexRouteImport } from './routes/_authenticated/certificates.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedSeminarsIdRouteImport } from './routes/_authenticated/seminars.$id'
import { Route as AuthenticatedExamsExamIdRouteImport } from './routes/_authenticated/exams.$examId'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses.$slug'
import { Route as AuthenticatedCertificatesIdRouteImport } from './routes/_authenticated/certificates.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSeminarsRouteImport } from './routes/_authenticated/admin.seminars'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminLicensesRouteImport } from './routes/_authenticated/admin.licenses'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminCpdRouteImport } from './routes/_authenticated/admin.cpd'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminGradingIndexRouteImport } from './routes/_authenticated/admin.grading.index'
import { Route as AuthenticatedExamsExamIdAttemptRouteImport } from './routes/_authenticated/exams.$examId.attempt'
import { Route as AuthenticatedAdminGradingAttemptIdRouteImport } from './routes/_authenticated/admin.grading.$attemptId'
import { Route as AuthenticatedExamsExamIdResultAttemptIdRouteImport } from './routes/_authenticated/exams.$examId.result.$attemptId'
import { Route as AuthenticatedCoursesSlugLessonsLessonIdRouteImport } from './routes/_authenticated/courses.$slug.lessons.$lessonId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyHashRoute = VerifyHashRouteImport.update({
  id: '/verify/$hash',
  path: '/verify/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeminarsRoute = AuthenticatedSeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistryRoute = AuthenticatedRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyLearningRoute = AuthenticatedMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLicenseRoute = AuthenticatedLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCpdRoute = AuthenticatedCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesIndexRoute =
  AuthenticatedCertificatesIndexRouteImport.update({
    id: '/certificates/',
    path: '/certificates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeminarsIdRoute = AuthenticatedSeminarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSeminarsRoute,
} as any)
const AuthenticatedExamsExamIdRoute =
  AuthenticatedExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const AuthenticatedCertificatesIdRoute =
  AuthenticatedCertificatesIdRouteImport.update({
    id: '/certificates/$id',
    path: '/certificates/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSeminarsRoute =
  AuthenticatedAdminSeminarsRouteImport.update({
    id: '/admin/seminars',
    path: '/admin/seminars',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/admin/resources',
    path: '/admin/resources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLicensesRoute =
  AuthenticatedAdminLicensesRouteImport.update({
    id: '/admin/licenses',
    path: '/admin/licenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCpdRoute = AuthenticatedAdminCpdRouteImport.update({
  id: '/admin/cpd',
  path: '/admin/cpd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGradingIndexRoute =
  AuthenticatedAdminGradingIndexRouteImport.update({
    id: '/admin/grading/',
    path: '/admin/grading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamIdAttemptRoute =
  AuthenticatedExamsExamIdAttemptRouteImport.update({
    id: '/attempt',
    path: '/attempt',
    getParentRoute: () => AuthenticatedExamsExamIdRoute,
  } as any)
const AuthenticatedAdminGradingAttemptIdRoute =
  AuthenticatedAdminGradingAttemptIdRouteImport.update({
    id: '/admin/grading/$attemptId',
    path: '/admin/grading/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamIdResultAttemptIdRoute =
  AuthenticatedExamsExamIdResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedExamsExamIdRoute,
  } as any)
const AuthenticatedCoursesSlugLessonsLessonIdRoute =
  AuthenticatedCoursesSlugLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedCoursesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/cpd': typeof AuthenticatedCpdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/license': typeof AuthenticatedLicenseRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/seminars': typeof AuthenticatedSeminarsRouteWithChildren
  '/verify/$hash': typeof VerifyHashRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/cpd': typeof AuthenticatedAdminCpdRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/seminars': typeof AuthenticatedAdminSeminarsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRouteWithChildren
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/seminars/$id': typeof AuthenticatedSeminarsIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/admin/grading/$attemptId': typeof AuthenticatedAdminGradingAttemptIdRoute
  '/exams/$examId/attempt': typeof AuthenticatedExamsExamIdAttemptRoute
  '/admin/grading/': typeof AuthenticatedAdminGradingIndexRoute
  '/courses/$slug/lessons/$lessonId': typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  '/exams/$examId/result/$attemptId': typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/cpd': typeof AuthenticatedCpdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/license': typeof AuthenticatedLicenseRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/seminars': typeof AuthenticatedSeminarsRouteWithChildren
  '/verify/$hash': typeof VerifyHashRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/cpd': typeof AuthenticatedAdminCpdRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/seminars': typeof AuthenticatedAdminSeminarsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRouteWithChildren
  '/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/seminars/$id': typeof AuthenticatedSeminarsIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/certificates': typeof AuthenticatedCertificatesIndexRoute
  '/admin/grading/$attemptId': typeof AuthenticatedAdminGradingAttemptIdRoute
  '/exams/$examId/attempt': typeof AuthenticatedExamsExamIdAttemptRoute
  '/admin/grading': typeof AuthenticatedAdminGradingIndexRoute
  '/courses/$slug/lessons/$lessonId': typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  '/exams/$examId/result/$attemptId': typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/cpd': typeof AuthenticatedCpdRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/license': typeof AuthenticatedLicenseRoute
  '/_authenticated/my-learning': typeof AuthenticatedMyLearningRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/registry': typeof AuthenticatedRegistryRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/seminars': typeof AuthenticatedSeminarsRouteWithChildren
  '/verify/$hash': typeof VerifyHashRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/cpd': typeof AuthenticatedAdminCpdRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/seminars': typeof AuthenticatedAdminSeminarsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/certificates/$id': typeof AuthenticatedCertificatesIdRoute
  '/_authenticated/courses/$slug': typeof AuthenticatedCoursesSlugRouteWithChildren
  '/_authenticated/exams/$examId': typeof AuthenticatedExamsExamIdRouteWithChildren
  '/_authenticated/seminars/$id': typeof AuthenticatedSeminarsIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/certificates/': typeof AuthenticatedCertificatesIndexRoute
  '/_authenticated/admin/grading/$attemptId': typeof AuthenticatedAdminGradingAttemptIdRoute
  '/_authenticated/exams/$examId/attempt': typeof AuthenticatedExamsExamIdAttemptRoute
  '/_authenticated/admin/grading/': typeof AuthenticatedAdminGradingIndexRoute
  '/_authenticated/courses/$slug/lessons/$lessonId': typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
  '/_authenticated/exams/$examId/result/$attemptId': typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/badges'
    | '/courses'
    | '/cpd'
    | '/dashboard'
    | '/exams'
    | '/license'
    | '/my-learning'
    | '/notifications'
    | '/profile'
    | '/promotions'
    | '/registry'
    | '/resources'
    | '/seminars'
    | '/verify/$hash'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/cpd'
    | '/admin/exams'
    | '/admin/licenses'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/seminars'
    | '/admin/settings'
    | '/admin/users'
    | '/certificates/$id'
    | '/courses/$slug'
    | '/exams/$examId'
    | '/seminars/$id'
    | '/api/public/bootstrap-admin'
    | '/admin/'
    | '/certificates/'
    | '/admin/grading/$attemptId'
    | '/exams/$examId/attempt'
    | '/admin/grading/'
    | '/courses/$slug/lessons/$lessonId'
    | '/exams/$examId/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/badges'
    | '/courses'
    | '/cpd'
    | '/dashboard'
    | '/exams'
    | '/license'
    | '/my-learning'
    | '/notifications'
    | '/profile'
    | '/promotions'
    | '/registry'
    | '/resources'
    | '/seminars'
    | '/verify/$hash'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/cpd'
    | '/admin/exams'
    | '/admin/licenses'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/resources'
    | '/admin/seminars'
    | '/admin/settings'
    | '/admin/users'
    | '/certificates/$id'
    | '/courses/$slug'
    | '/exams/$examId'
    | '/seminars/$id'
    | '/api/public/bootstrap-admin'
    | '/admin'
    | '/certificates'
    | '/admin/grading/$attemptId'
    | '/exams/$examId/attempt'
    | '/admin/grading'
    | '/courses/$slug/lessons/$lessonId'
    | '/exams/$examId/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/badges'
    | '/_authenticated/courses'
    | '/_authenticated/cpd'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/license'
    | '/_authenticated/my-learning'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/promotions'
    | '/_authenticated/registry'
    | '/_authenticated/resources'
    | '/_authenticated/seminars'
    | '/verify/$hash'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/cpd'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/licenses'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/seminars'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/certificates/$id'
    | '/_authenticated/courses/$slug'
    | '/_authenticated/exams/$examId'
    | '/_authenticated/seminars/$id'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/admin/'
    | '/_authenticated/certificates/'
    | '/_authenticated/admin/grading/$attemptId'
    | '/_authenticated/exams/$examId/attempt'
    | '/_authenticated/admin/grading/'
    | '/_authenticated/courses/$slug/lessons/$lessonId'
    | '/_authenticated/exams/$examId/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyHashRoute: typeof VerifyHashRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$hash': {
      id: '/verify/$hash'
      path: '/verify/$hash'
      fullPath: '/verify/$hash'
      preLoaderRoute: typeof VerifyHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seminars': {
      id: '/_authenticated/seminars'
      path: '/seminars'
      fullPath: '/seminars'
      preLoaderRoute: typeof AuthenticatedSeminarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry': {
      id: '/_authenticated/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-learning': {
      id: '/_authenticated/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AuthenticatedMyLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/license': {
      id: '/_authenticated/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AuthenticatedLicenseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cpd': {
      id: '/_authenticated/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof AuthenticatedCpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates/': {
      id: '/_authenticated/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthenticatedCertificatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seminars/$id': {
      id: '/_authenticated/seminars/$id'
      path: '/$id'
      fullPath: '/seminars/$id'
      preLoaderRoute: typeof AuthenticatedSeminarsIdRouteImport
      parentRoute: typeof AuthenticatedSeminarsRoute
    }
    '/_authenticated/exams/$examId': {
      id: '/_authenticated/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/courses/$slug': {
      id: '/_authenticated/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/certificates/$id': {
      id: '/_authenticated/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/certificates/$id'
      preLoaderRoute: typeof AuthenticatedCertificatesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/seminars': {
      id: '/_authenticated/admin/seminars'
      path: '/admin/seminars'
      fullPath: '/admin/seminars'
      preLoaderRoute: typeof AuthenticatedAdminSeminarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/licenses': {
      id: '/_authenticated/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AuthenticatedAdminLicensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cpd': {
      id: '/_authenticated/admin/cpd'
      path: '/admin/cpd'
      fullPath: '/admin/cpd'
      preLoaderRoute: typeof AuthenticatedAdminCpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/grading/': {
      id: '/_authenticated/admin/grading/'
      path: '/admin/grading'
      fullPath: '/admin/grading/'
      preLoaderRoute: typeof AuthenticatedAdminGradingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examId/attempt': {
      id: '/_authenticated/exams/$examId/attempt'
      path: '/attempt'
      fullPath: '/exams/$examId/attempt'
      preLoaderRoute: typeof AuthenticatedExamsExamIdAttemptRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdRoute
    }
    '/_authenticated/admin/grading/$attemptId': {
      id: '/_authenticated/admin/grading/$attemptId'
      path: '/admin/grading/$attemptId'
      fullPath: '/admin/grading/$attemptId'
      preLoaderRoute: typeof AuthenticatedAdminGradingAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examId/result/$attemptId': {
      id: '/_authenticated/exams/$examId/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/exams/$examId/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedExamsExamIdResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedExamsExamIdRoute
    }
    '/_authenticated/courses/$slug/lessons/$lessonId': {
      id: '/_authenticated/courses/$slug/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/courses/$slug/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedCoursesSlugLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedCoursesSlugRoute
    }
  }
}

interface AuthenticatedCoursesSlugRouteChildren {
  AuthenticatedCoursesSlugLessonsLessonIdRoute: typeof AuthenticatedCoursesSlugLessonsLessonIdRoute
}

const AuthenticatedCoursesSlugRouteChildren: AuthenticatedCoursesSlugRouteChildren =
  {
    AuthenticatedCoursesSlugLessonsLessonIdRoute:
      AuthenticatedCoursesSlugLessonsLessonIdRoute,
  }

const AuthenticatedCoursesSlugRouteWithChildren =
  AuthenticatedCoursesSlugRoute._addFileChildren(
    AuthenticatedCoursesSlugRouteChildren,
  )

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRouteWithChildren
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRouteWithChildren,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedExamsExamIdRouteChildren {
  AuthenticatedExamsExamIdAttemptRoute: typeof AuthenticatedExamsExamIdAttemptRoute
  AuthenticatedExamsExamIdResultAttemptIdRoute: typeof AuthenticatedExamsExamIdResultAttemptIdRoute
}

const AuthenticatedExamsExamIdRouteChildren: AuthenticatedExamsExamIdRouteChildren =
  {
    AuthenticatedExamsExamIdAttemptRoute: AuthenticatedExamsExamIdAttemptRoute,
    AuthenticatedExamsExamIdResultAttemptIdRoute:
      AuthenticatedExamsExamIdResultAttemptIdRoute,
  }

const AuthenticatedExamsExamIdRouteWithChildren =
  AuthenticatedExamsExamIdRoute._addFileChildren(
    AuthenticatedExamsExamIdRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsExamIdRoute: typeof AuthenticatedExamsExamIdRouteWithChildren
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsExamIdRoute: AuthenticatedExamsExamIdRouteWithChildren,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedSeminarsRouteChildren {
  AuthenticatedSeminarsIdRoute: typeof AuthenticatedSeminarsIdRoute
}

const AuthenticatedSeminarsRouteChildren: AuthenticatedSeminarsRouteChildren = {
  AuthenticatedSeminarsIdRoute: AuthenticatedSeminarsIdRoute,
}

const AuthenticatedSeminarsRouteWithChildren =
  AuthenticatedSeminarsRoute._addFileChildren(
    AuthenticatedSeminarsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedCpdRoute: typeof AuthenticatedCpdRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedLicenseRoute: typeof AuthenticatedLicenseRoute
  AuthenticatedMyLearningRoute: typeof AuthenticatedMyLearningRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedRegistryRoute: typeof AuthenticatedRegistryRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSeminarsRoute: typeof AuthenticatedSeminarsRouteWithChildren
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminCpdRoute: typeof AuthenticatedAdminCpdRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminLicensesRoute: typeof AuthenticatedAdminLicensesRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSeminarsRoute: typeof AuthenticatedAdminSeminarsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedCertificatesIdRoute: typeof AuthenticatedCertificatesIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCertificatesIndexRoute: typeof AuthenticatedCertificatesIndexRoute
  AuthenticatedAdminGradingAttemptIdRoute: typeof AuthenticatedAdminGradingAttemptIdRoute
  AuthenticatedAdminGradingIndexRoute: typeof AuthenticatedAdminGradingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedCpdRoute: AuthenticatedCpdRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedLicenseRoute: AuthenticatedLicenseRoute,
  AuthenticatedMyLearningRoute: AuthenticatedMyLearningRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedRegistryRoute: AuthenticatedRegistryRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSeminarsRoute: AuthenticatedSeminarsRouteWithChildren,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminCpdRoute: AuthenticatedAdminCpdRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
  AuthenticatedAdminLicensesRoute: AuthenticatedAdminLicensesRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminSeminarsRoute: AuthenticatedAdminSeminarsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedCertificatesIdRoute: AuthenticatedCertificatesIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCertificatesIndexRoute: AuthenticatedCertificatesIndexRoute,
  AuthenticatedAdminGradingAttemptIdRoute:
    AuthenticatedAdminGradingAttemptIdRoute,
  AuthenticatedAdminGradingIndexRoute: AuthenticatedAdminGradingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyHashRoute: VerifyHashRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
