// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession()
    const expiresAt = data.session?.expires_at ?? 0
    // Refresh proactively if the access token has expired or is within 30s of expiry,
    // otherwise the server middleware rejects it with "Invalid token".
    if (data.session && expiresAt * 1000 - Date.now() < 30_000) {
      const { data: refreshed } = await supabase.auth.refreshSession()
      if (refreshed.session) data = { session: refreshed.session } as typeof data
      else {
        // Refresh token is dead — sign out so the user is sent back to /login.
        await supabase.auth.signOut()
        data = { session: null } as typeof data
      }
    }
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
